# Generated by Django 4.2 on 2025-07-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, to='weather.district')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ward', models.OneToOneField(db_column='ward_id', on_delete=django.db.models.deletion.CASCADE, to='weather.ward')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='HydrologyStation',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.location')),
            ],
            options={
                'db_table': 'hydrology_stations',
            },
        ),
        migrations.CreateModel(
            name='HydrologyData',
            fields=[
                ('hydrology_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.FloatField()),
                ('measurement_time', models.DateTimeField()),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='weather.hydrologystation')),
            ],
            options={
                'db_table': 'hydrology_data',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='weather.province'),
        ),
    ]
